services:
  github-runner:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      - REPO_URL=https://github.com/jcquinlan/ash1-oasis
      - RUNNER_NAME=ash1-runner
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_WORKDIR=/tmp/github-runner
      - LABELS=self-hosted,linux,ash1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-work:/tmp/github-runner
    security_opt:
      - label:disable

volumes:
  runner-work:
